apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: lab3
spec:
  containers:
  - name: busybox-container
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do date >> /shared-data/date.log; sleep 5; done"
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
  - name: nginx-server
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    hostPath:
      path: /c/Users/macie/SharedData
      type: DirectoryOrCreate