apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops
              image: maciejciukaj/zad2gitops
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/maciejciukaj/lab10_config_repo.git /tmp/lab10_config_repo && find /tmp/lab10_config_repo -name '*.yaml' -exec kubectl apply -f {} \;
